### ISSUE TITLE
Implement `AccountData`

### ISSUE THREAD

**Issue by 0xLucqs** [keep-starknet-strange/madara#100]
# Description

Implement `AccountInfo` with fields relevant to Starknet in `AccountData`

# Resources

https://docs.substrate.io/reference/account-data-structures/#account

**Comment by 4meta5** [comment]
> Implement AccountInfo with fields relevant to Starknet in AccountData

@abdelhamidbakhta @LucasLvy what fields are relevant to Starknet?

I see `pallet_balances::AccountData<Balance>` is used, what fields must be added/removed for Starknet?

```rust
pallet_balances::AccountData<Balance> {
         /// Non-reserved part of the balance. There may still be restrictions on this, but it is the
	/// total pool what may in principle be transferred, reserved and used for tipping.
	///
	/// This is the only balance that matters in terms of most operations on tokens. It
	/// alone is used to determine the balance when in the contract execution environment.
	pub free: Balance,
	/// Balance which is reserved and may not be used at all.
	///
	/// This can still get slashed, but gets slashed last of all.
	///
	/// This balance is a 'reserve' balance that other subsystems use in order to set aside tokens
	/// that are still 'owned' by the account holder, but which are suspendable.
	/// This includes named reserve and unnamed reserve.
	pub reserved: Balance,
	/// The amount that `free` may not drop below when withdrawing for *anything except transaction
	/// fee payment*.
	pub misc_frozen: Balance,
	/// The amount that `free` may not drop below when withdrawing specifically for transaction
	/// fee payment.
	pub fee_frozen: Balance,
}
```

**Comment by LucasLvy** [comment]
For now only free seems relevant as starknet doesn't have a native token all the logic is implemented in the smart contract we don't need those differences

**Comment by 4meta5** [comment]
`pallet_balances::Config::AccountStore` has the bound `StoredMap<Self::AccountId, AccountData<Self::Balance>>` [docs](https://paritytech.github.io/substrate/master/pallet_balances/pallet/trait.Config.html#associatedtype.AccountStore) so `frame_system::Config::AccountInfo` must be set to `AccountData<Self::Balance>` now with all of its fields.

We could make the `pallet_balances::Config::AccountStore` bound more generic so it's `StoredMap<Self::AccountId, T::AccountData>` where T::AccountData could be T::Balance for this case, but it requires a lot of refactoring in pallet_balances  because `AccountData<Balance>` struct is used everywhere now...

**Comment by abdelhamidbakhta** [comment]
@LucasLvy can you please help @4meta5

**Comment by LucasLvy** [comment]
I suggest we pause this until we have the fees which will bring a bit more clarity in this

**Comment by abdelhamidbakhta** [comment]
> I suggest we pause this until we have the fees which will bring a bit more clarity in this

ok. @4meta5 you want to tackle something else meanwhile ?

**Comment by LucasLvy** [comment]
We switched to unsigned txs so not relevant anymore
