### ISSUE TITLE
fix: fee and resource calculation

### ISSUE THREAD

**Issue by apoorvsadana** [keep-starknet-strange/madara#1096]
After #992 is merged, we need to update the code to calculate fees and the actual resources. This PR rebases based on the new blockifier logic which has rejected transactions. We can read more about that logic [here](https://github.com/starkware-libs/blockifier/blob/e8ee613d05cf9c55bdb10b871b59365fca04b6ee/crates/blockifier/src/transaction/account_transaction.rs#L706). However, the correct logic isn't implemented in Madara yet, we need to do that.

**Comment by apoorvsadana** [comment]
That is one part but I believe there are also some checks related to reverted transactions missing from Madara which are there in the blockifier  - https://github.com/keep-starknet-strange/madara/pull/992#discussion_r1321377932

**Comment by EvolveArt** [comment]
Was this fixed cc @apoorvsadana @tdelabro ?

**Comment by apoorvsadana** [comment]
I didn't work on it. Not sure if @tdelabro was doing so.

**Comment by tdelabro** [comment]
I'm not. I will add it to the board and see if a contributor want to work on this

**Comment by andresmayorca** [comment]
I'm interested

**Comment by tdelabro** [comment]
Hey, all good?

**Comment by andresmayorca** [comment]
Hey! yeah, all good

**Comment by tdelabro** [comment]
Cool. You are making progress?
Don't hesitate to ask for help if needed.

**Comment by andresmayorca** [comment]
Yes! I've made some progress 
and of course! I'll ask

**Comment by tdelabro** [comment]
Hey,

So, I was reading the blockifier's code again, and I think we should use it.

```rust
#[derive(Debug)]
pub struct CachedState<S: StateReader> {
    pub state: S,
    // Invariant: read/write access is managed by CachedState.
    cache: StateCache,
    class_hash_to_class: ContractClassMapping,
    // Invariant: managed by CachedState.
    global_class_hash_to_class: GlobalContractCache,
}
```

and this one:
```rust
pub type TransactionalState<'a, S> = CachedState<MutRefState<'a, CachedState<S>>>;
```

They define this cached state that allows them to revert the storage to its initial state, but also to change this.
We didn't use it before because nothing was charged for reverted tx so we prefer to use substrate extrinsic reversion logic instead.

I think all you have to do, is wrap our state adapter into a CachedState and a TransactionalState, and then use the execution method they define, rather than the ones I created under `crates/primitives/transactions/src/execution.rs`.

You can get rid of those, and use blockifier native code instead.

Wdyt?

Also @apoorvsadana what is your opinion?

**Comment by andresmayorca** [comment]
Hey, I like this. I had thought of something similar but it's much better to do it this way.

I'll do it like this 🫡

**Comment by tdelabro** [comment]
in https://github.com/keep-starknet-strange/madara/pull/1204 I changed stuffs regarding fees. We are coming back closer to blockifier, it should help with your work.
When do you think you will be able to push something?

**Comment by tdelabro** [comment]
@andresmayorca how is it going?

**Comment by andresmayorca** [comment]
Hey! I had not read this, this week I'll pushing everything

**Comment by tdelabro** [comment]
@andresmayorca Any update on this one?

**Comment by apoorvsadana** [comment]
@tdelabro I guess this is completed right?

**Comment by tdelabro** [comment]
@apoorvsadana or it will when we get rid of our custom tx execution code
