### ISSUE TITLE
Tracking issue: L1->L2 messaging 

### ISSUE THREAD

**Issue by tdelabro** [keep-starknet-strange/madara#1132]
Todo:
- [x] #1156
- [x] #1177
-  make it expose an async method that contains an infinite loop
- in this loop pull ethereum events emitted by the starknet core contract
- when events are emitted add a TX to the mempool
- in node/src/services.rs use `task_manager.spawn_essential_handle()` to spawn this new async task

Additional questions:
- should we have a retry mechanism? The memepool already has retry. What additional case should it cover?
- do we have enough tests for l1HandlerTx? I'm not sure. It may have been a bit forgoten as it wasn't implemented yet
- is there some sort of message ordering?

**Comment by tchataigner** [comment]
> should we have a retry mechanism? The memepool already has retry. What additional case should it cover?
Loved the _memepool_ typo :laughing: 

I would say that even withtout talking about tx validity or execution we could have any Rust error along the way that would make it so that the tx do not get executed. If that happen we need to have a way of tracking it and re-submitting the tx. So I would say that yes, such a mechanism seems interesting.

> do we have enough tests for l1HandlerTx? I'm not sure. It may have been a bit forgoten as it wasn't implemented yet

We could add writing tests for this as a task to tackle. However, as this is part of our flow we might also consider that the test we will write for our features are the one that will test it. What do you think?

On that note, along with unit tests, I think we should specify to add more E2E tests in our devs to be done? Wdyt?

 > is there some sort of message ordering?

After diging a little bit I think ordering (at least for L1 -> L2) is important. Looking at the [implementation of `sendMessageToL2`](https://github.com/keep-starknet-strange/zaun/blob/0cd36eb3eedad85ec735f031dfe789c38693aac9/lib/starknet/StarknetMessaging.sol#L133), it seems that the nonce is actually set [at the start of the whole process ](https://docs.starknet.io/documentation/architecture_and_concepts/Network_Architecture/messaging-mechanism/#l1-l2-messages). So we should respect nonce order for this flow. 

For the L2 -> L1 flow I think that the order of the messages to L1 will be based on the ordering of the messages on L2, so we should follow that.

**Comment by tdelabro** [comment]
About l1 to l2 message orderign, i asked internaly and the answer is that the current sequencer do respect the order in which the event have been emmited on ethereum when executing them on starknet, but he does not enforce it at the protocol level.

**Comment by tchataigner** [comment]
Alright so I guess we should try to respect the same flow 😄

**Comment by bidzyyys** [comment]
We need an issue to provide proper test coverage for all tx types (for `validate_unsigned`)

**Comment by tdelabro** [comment]
I created #1163
