### ISSUE TITLE
feat: allow `dev` nodes to use instant seal

### ISSUE THREAD

**Issue by tdelabro** [keep-starknet-strange/madara#1144]
# Feature Request

Right now in `load_spec`
```rust
Ok(match id {
            "dev" => {
                let enable_manual_seal = self.run.sealing.map(|_| true);
```
Meaning event if ` self.run.sealing` was of value `Some(Sealing::Instant)` we would still use manual sealing 

@EvolveArt pointed out that enableing it may involve solving this TODO: https://github.com/keep-starknet-strange/madara/blob/main/crates/node/src/service.rs#L319

**Comment by kalaninja** [comment]
Can this be assigned to me, please?

**Comment by tdelabro** [comment]
Give a look (and a review) to https://github.com/keep-starknet-strange/madara/pull/1165, it is modifying things in the same code area as you will :)

**Comment by tdelabro** [comment]
Hey, all good?

**Comment by kalaninja** [comment]
Hey @tdelabro I honestly don't see any problems with the source code. It seems to be set up correctly. Furthermore, I tested it locally and both instant and manual sealing seem to work correctly. I think the source of confusion originates in substrate since both instant and manual sealing are located inside manual-sealing module, so the naming here is confusing (both manual and instant sealing are referred as manual).

Another source of confusion might be that  `enable_manual_seal` actually doesn't enable any type of sealing, but overrides timestamp behavior in aura pallet.

Considering that message
> TODO: https://github.com/keep-starknet-strange/madara/blob/main/crates/node/src/service.rs#L319

It also seems to be irrelevant. `commands_stream` is actually used and it seems to be properly set up.

For now, I can propose improving log messages, fixing vars/args naming and the type of `enable_manual_seal: Option<bool>` seem redundant to me, `bool` alone should be enough.

**Comment by tdelabro** [comment]
Okay. Sound good. Go ahead with the proposed improvements
