### ISSUE TITLE
dev: refactor `LAST_SYNCED_L1_BLOCK` to be more clear

### ISSUE THREAD

**Issue by apoorvsadana** [keep-starknet-strange/madara#1335]
Right now, Madara fetches the event `LogMessageToL2` from Ethereum and accordingly creates a tx on the chain. Every time we get an event, we process it and update `LAST_SYNCED_L1_BLOCK` to the block number of the latest event. The name `LAST_SYNCED_L1_BLOCK` however is not accurate. The issue with this is that if there are no events from block n to block n+t, then `LAST_SYNCED_L1_BLOCK` won't be updated. So we want to refactor this variable to actually be a pair of

1. Block number
2. Event index

Where block_number represents the last_synced_l1_block_with_event and the event index represents the index of the event in the block.

**Comment by okhaimie-dev** [comment]
I'd love to try this out.

**Comment by dangush** [comment]
Hi, I'll pick this up!

**Comment by MSghais** [comment]
Hi, can I pick this one please?

I'm new to this repo, I would love to have some information on what is the best way to modify it, please.
I think we have few solutions: 

1.  Add others variable on top of it: 

- Add others columns in the DB columns, 
- add static_keys to get the LAST_L1_EVENT_INDEX
- Save also this variable on the DB 
- Do check in the L1_MESSAGES worker.rs to also update if we have others event index or not  in this block.

3. Modify struct of backend.messaging(): 

    a. Modify the MESSAGING columns to be an Hash in :
    https://github.com/keep-starknet-strange/madara/blob/bd1898aec7004ea08b5fedaf515012d44a29a14f/crates/client/db/src/lib.rs#L64
    
    b. Modify the messaging for GET and UPDATE functions of LAST_SYNCED_L1_BLOCK here:
    
    https://github.com/keep-starknet-strange/madara/blob/bd1898aec7004ea08b5fedaf515012d44a29a14f/crates/client/db/src/messaging_db.rs#L17

  c. Update the Client for L1_MESSAGE worker accordingly: 
https://github.com/keep-starknet-strange/madara/blob/bd1898aec7004ea08b5fedaf515012d44a29a14f/crates/client/l1-messages/src/worker.rs#L34

**Comment by dangush** [comment]
Hi, reposting some questions sent to TG (my bad, should have posted here)

I've opened a PR with what seem as the relevant changes, but I would like to develop some tests for this part of the code to make sure. I'm trying to orient myself around the testing setup, and would love some pointers on this. 

I took a look at the events-related tests, but it doesn't seem like those tests are relevant to processing event messages from the L1. Since I would need a mock db to test writing and reading this block number data, should I extend the `pallet_starknet` tests?

Also want to confirm I understand in general- how are messages from the L1 submitted to the madara node? Is it just through the RPC endpoint, done by some relayer?

Appreciate any help, looking forward to getting acquainted with this codebase and contributing more deeply.

**Comment by apoorvsadana** [comment]
Sorry for the confusion guys. Looks like @dangush has made a PR already so I have assigned the issue to him, @MSghais can you pick some other issue if possible.

@dangush, you can refer to starknet-e2e-tests for testing L1 messages. However, I am not sure if we can test the db changes you make here with e2e tests. I haven't reviewed the PR yet.

**Comment by dangush** [comment]
Hi @apoorvsadana thanks for the pr review, I've set it to open so it can be merged, since it seems testing this isn't super critical. 

I took a look through the e2e tests, but am struggling to understand the relationship between the madara instance and starknet contract / anvil instance in the `Context` struct here
* https://github.com/keep-starknet-strange/madara/blob/d818e8393657d2a0c861ef871d3888cfa2de06fb/starknet-e2e-test/ethereum_e2e_settlement.rs#L22-L26

in order to write a test. 

I can see there's logic for launching madara and creating blocks, but would it be possible to also read the state of the db using the MadaraNode wrapper or MadaraClient rpc in MadaraRunner?
https://github.com/keep-starknet-strange/madara/blob/d818e8393657d2a0c861ef871d3888cfa2de06fb/madara-test-runner/src/lib.rs#L28-L31

Would love some pointers on how I should go about this, if this is going in the right direction.
