### ISSUE TITLE
feat: Fix benchmarking

### ISSUE THREAD

**Issue by 0xLucqs** [keep-starknet-strange/madara#1357]
It's impossible to locally start the benchmark because it misses some files and deps

**Comment by aniketpr01** [comment]
@LucasLvy can i take this?

**Comment by aniketpr01** [comment]
yes @tdelabro, need some context in fixing it.
There has been a force push from this merge
https://github.com/keep-starknet-strange/madara/pull/1080
This commit seems to be removing tests folder
https://github.com/keep-starknet-strange/madara/commit/64246edeeafb6bf7e617ddc806541d97fd97d11d
can you review and confirm if this push was expected or needs to be reverted back in order to run tests and benchmarking on it

**Comment by tdelabro** [comment]
@LucasLvy can you add more context? Maybe the command you run, so @aniketpr01 can reproduce

**Comment by tdelabro** [comment]
@apoorvsadana @EvolveArt Is this benchmark directory still relevant? Don't we want to replace it by Gomu?

If so the issue could just be to `rm` this directory

**Comment by apoorvsadana** [comment]
Ya it's irrelevant afaik @tdelabro. We should have gomu gomu instead of this.

**Comment by LucasLvy** [comment]
also need to change the ci

**Comment by tdelabro** [comment]
@aniketpr01 Can you do this? rm the directory and change the CI

**Comment by aniketpr01** [comment]
@tdelabro yes
