### ISSUE TITLE
dev: Remove hardcoded block time in `get_transaction_receipt`

### ISSUE THREAD

**Issue by LucasLvy** [keep-starknet-strange/madara#1370]
When a transaction hasn't been mined we wait for the hardcoded block time in the rpc. Remove that and make it dynamic

**Comment by 0xethernet** [comment]
Hey can I take this one?

**Comment by 0xethernet** [comment]
Actually it sounds odd to wait in the rpc. Let's say that the block time is similar to mainnet it would mean waiting for a whole minute or 2. I suggest we don't wait for anything and we just answer tx not found. What do you think ? @LucasLvy

**Comment by LucasLvy** [comment]
@tdelabro ?

**Comment by tdelabro** [comment]
The reason we did it is because wallets send a transaction and then immediately ask for its receipt. Because we don't process it immediately we return TxHashNotFound and the wallet report an error to the user.
@lana-shanghai can you confirm that is the reason we did that?

Imo a more acceptable solution would be to query the TX pool to see the pending tx there. And return a PendingTxReceipt

**Comment by tdelabro** [comment]
@0xethernet are you actively working on it?

**Comment by 0xethernet** [comment]
Yes !

**Comment by tdelabro** [comment]
Great! Keep us updated. Don't hesitate to push even if it's not 100% finished. 
We are here to help

**Comment by 0xethernet** [comment]
The receipts for pending or accepted on l2 are roughly the same on starknet. The equivalent of our case would be the received state according to [that](https://docs.starknet.io/documentation/architecture_and_concepts/Network_Architecture/transaction-life-cycle/#transaction_flow) which does not seem to be handled by the `MaybePendingTransactionReceipt`. What do you think I should do ?

**Comment by tdelabro** [comment]
@0xethernet I don't understand you question. Can you give me more context and be a bit more precise? What are your option rn?

**Comment by 0xethernet** [comment]
In madara there are only 2 states for a transaction:
- executed (which is equivalent to Accepted on l2)
- Received (which is equivalent to received by the sequencer but not executed yet)
The return type of `get_transaction_receipt` is `MaybePendingTransactionReceipt` which represents the `Pending || Accepted on L2` receipt (both require execution).
So my options are to either change the return type of `get_transaction_receipt` to an `enum { Received, MaybePending }`. Or i can just wait as we're already doing and get the real block time by importing it from the config crate instead of hardcoding 6s

**Comment by tdelabro** [comment]
You cannot change the type of the RPC `get_transaction_receipt`. Are you talking about another symbol with the same name?

**Comment by tdelabro** [comment]
I just don't get the issue here.

What you have to do is:
1) Try to get the tx from the existing blocks with `block_hash_from_transaction_hash(H256::from(transaction_hash.to_bytes_be()))`
2) If `1)` failed, try to get it from the pool. In the pool a tx can be in the `ready` or `future` lists, so:
 a) get the list of the [ready](https://paritytech.github.io/polkadot-sdk/master/sc_service/trait.TransactionPool.html#tymethod.ready) transactions
 b) if it's not there, get the list of the [future](https://paritytech.github.io/polkadot-sdk/master/sc_service/trait.TransactionPool.html#tymethod.futures) transactions
 
 If it's in none of those returns an error.
 If it is in a past block returns a `MaybePendingTransactionReceipt::Receipt` instance.
 If it's in the tx poll returns a `MaybePendingTransactionReceipt::Pending` instance.

**Comment by tdelabro** [comment]
You can probably do it by calling: https://paritytech.github.io/polkadot-sdk/master/sp_consensus_aura/trait.AuraApi.html#method.slot_duration

Or you could look at the current block number, and loop until this value has changed. I think this would be our most versatile and resilient option.

**Comment by tdelabro** [comment]
👆 This will work for now.
But if you wait a little bit I asked internally what should be the behavior in this situation, we should get an answer soon

**Comment by tdelabro** [comment]
Apparently, we should just remove an error, like we did initially. 
I'm doing it in #1398

@lana-shanghai we were probably wrong thinking this was the thing breaking our wallet integration

**Comment by tdelabro** [comment]
@0xethernet did you spent some amount of time working on this?

**Comment by 0xethernet** [comment]
Yes a few hours

**Comment by tdelabro** [comment]
@0xethernet kay, I reward you with a lil something in STRK
