### ISSUE TITLE
bug(rpc-tests): Fail on running tests subsequently

### ISSUE THREAD

**Issue by antiyro** [keep-starknet-strange/madara#1380]
# Bug Report

Currently the only way to pass all starknet-rpc-tests is to run the tests all togethers. Before then it was possible to run tests individually without depending on the others, this is possibly due to bad account balances manipulations.

Please comment under here if you observe reasons for individual tests to fail.

**Comment by tdelabro** [comment]
I believe in the past it wasn't always that way.

**Comment by azurwastaken** [comment]
Would like to give it a look @EvolveArt

**Comment by tdelabro** [comment]
@azurwastaken are you still working on this?

**Comment by azurwastaken** [comment]
> @azurwastaken are you still working on this?

Yes, have been really busy recently so I couldn’t make much progress.

I saw that most of test can be run individually as long as you restart madara between each launch so its probably caused by a to low balance as @antiyro said in the first message.

For the other ones who dont work even when we restart madara, i guess that they relate on other test to setup their initial state so i need to find out those relationship.

**Comment by tdelabro** [comment]
@azurwastaken okay cool, keep up the good work!

**Comment by tdelabro** [comment]
@azurwastaken what is the situation here?

**Comment by azurwastaken** [comment]
> @azurwastaken what is the situation here?

Currently on holiday and had no time to work on it, if urgent i can leave this one to someone else, otherwise i’ll work on it when im back 🫡

**Comment by tdelabro** [comment]
@azurwastaken still on it?

**Comment by maksimryndin** [comment]
Hi @tdelabro! Can I take this issue? I believe it is nice to onboard on the codebase

**Comment by tdelabro** [comment]
repository archived in favor of https://github.com/madara-alliance/madara
