### ISSUE TITLE
bug: read only finalised `LogMessageToL2` events

### ISSUE THREAD

**Issue by apoorvsadana** [keep-starknet-strange/madara#1521]
Currently, if I understand it correctly, Madara reads events instantly from the L1 even if they arne't finalised. First, we need to confirm this is the case. If it yes, we need to change this so that only finalised events are read.

**Comment by prtk418** [comment]
@apoorvsadana Picking this up

**Comment by apoorvsadana** [comment]
Sure, assgined

**Comment by prtk418** [comment]
Yes, right now Madara starts processing immediately as it receives events. Confirmed by checking code and logging L1 current block number and block number at which event was dispatched, both are same - meaning waiting for block confirmations are not in place.

Approach we could take is - instead of streaming events, we can watch for new blocks. When a new block is produced we can iterate through events from `latest_block - block_confirmation` block and process them 

@apoorvsadana what do you think?

**Comment by apoorvsadana** [comment]
How will you watch for new blocks @prtk418? @tdelabro, are you aware how many blocks does Starknet wait for currently before it reads a message, is it 2 epochs?

**Comment by prtk418** [comment]
> How will you watch for new blocks @prtk418? @tdelabro, are you aware how many blocks does Starknet wait for currently before it reads a message, is it 2 epochs?

Similar to `stream_with_meta` for events we have `watch_blocks` in ethers that we can use for watching blocks. Ref - https://docs.rs/ethers/latest/ethers/middleware/trait.Middleware.html#method.watch_blocks

**Comment by prtk418** [comment]
As discussed with @apoorvsadana , its better to rely on rpc to tell us finalized blocks to be 100% deterministic and efficient. Will come back to this once we migrate to [alloy](https://github.com/keep-starknet-strange/madara/issues/1528)

**Comment by tdelabro** [comment]
blocked by #1532 1528

**Comment by tdelabro** [comment]
still blocked

**Comment by tdelabro** [comment]
repository archived in favor of https://github.com/madara-alliance/madara
