### ISSUE TITLE
bug: gomu gomu yields InvalidNonce errors

### ISSUE THREAD

**Issue by apoorvsadana** [keep-starknet-strange/madara#1541]
Running gomu gomu on Madara gives invalid nonce errors. Need to understand why this happens. The validate_unsigned logic inside Madara might be a good starting point.

**Comment by swetshaw** [comment]
I can take this up

**Comment by apoorvsadana** [comment]
Assinged

**Comment by swetshaw** [comment]
### Problem
- When running [gomu gomu](https://github.com/keep-starknet-strange/gomu-gomu-no-gatling) with madara, gomu gomu exits with an error shown in image below
<img width="1226" alt="Screenshot 2024-04-01 at 11 34 42 AM" src="https://github.com/keep-starknet-strange/madara/assets/26214362/3680556b-91a8-438b-b4ee-caa182d9d310">
- At the same time the following invalid nonce error gets logged in madara node

<img width="994" alt="Screenshot 2024-04-01 at 11 36 22 AM" src="https://github.com/keep-starknet-strange/madara/assets/26214362/69d0b81c-709b-4bee-a5ae-9c4b3f377735">

### Observation
- Although all the transactions fired by gomu gomu goes through, the invalid nonce error pops up only when it waits for the transaction. That is, it calls `wait_for_tx` function defined [here](https://github.com/keep-starknet-strange/gomu-gomu-no-gatling/blob/b49c1a5a18d7d9a6986ccc87fba5a6638687ff8e/src/actions/goose.rs#L378)

_Note_ : After firing all the transactions -- gomu looks for transaction receipt for the last transaction hash

### Reason for invalid nonce
- Every `wait_for_tx` function call in gomu triggers the function `get_transaction_receipt` in the madara node [here](https://github.com/keep-starknet-strange/madara/blob/943f323acab8560d256571eda0fbe985172029c8/crates/client/rpc/src/lib.rs#L1427)
- This is the function trail:  `get_transaction_receipt` --> `prepare_tx_receipt` --> `simulate_tx` --> `simulate_user_tx` -->  `simulate_transactions` --> `simulate_transactions_inner` --> `execute_transaction_with_state_diff` --> `execute` --> `handle_nonce_and_check_fee_balance` --> `handle_nonce`
- `handle_nonce` checks for the nonce [here](https://github.com/keep-starknet-strange/madara/blob/943f323acab8560d256571eda0fbe985172029c8/crates/primitives/transactions/src/execution.rs#L317) and errors out with invalid nonce if check fails
- It's obvious the check will fail because the first set of transactions have not yet been completed yet, hence the value of nonce is still at say 1, but gomu is trying to look for transaction receipt for transaction N (N>1, nonce > 1) 

### Potential solution
- We can avoid simulating transaction for the `get_transaction_receipt`, it should simply query for the transaction hash and return it's status

### Notes:
- Madara `main` branch was tested with gomu's `main` branch as well as the PR by LimeChain [here](https://github.com/keep-starknet-strange/gomu-gomu-no-gatling/pull/46)
- Tested with Gomu's config in `default.yaml` with following settings:
- 1
    ```
     run:
      num_erc20_transfers: 2
      num_erc721_mints: 0
      concurrency: 1
    ```
- 2
    ```
     run:
      num_erc20_transfers: 1000
      num_erc721_mints: 1000
      concurrency: 1
    ```
- 3
    ```
     run:
      num_erc20_transfers: 1000
      num_erc721_mints: 1000
      concurrency: 5
    ```
- And the same error `Transaction execution failed during simulation: Invalid transaction nonce of contract` were observed

**Comment by swetshaw** [comment]
It seems the PR #1455 should fix this issue. Need to test this again with the PR

**Comment by tdelabro** [comment]
@swetshaw @Angel-Petrov can you confirm this had been fixed?

**Comment by apoorvsadana** [comment]
Yes @tdelabro, it's been fixed
