### ISSUE TITLE
feat: RPC - starknet_syncing

### ISSUE THREAD

**Issue by abdelhamidbakhta** [keep-starknet-strange/madara#205]
Returns an object about the sync status, or false if the node is not synching

**Comment by zediogoviana** [comment]
I can try to tackle this one

**Comment by abdelhamidbakhta** [comment]
> I can try to tackle this one

Sure, assigned to you

**Comment by zediogoviana** [comment]
Hey @abdelhamidbakhta 👋 

So, after looking at the endpoint specification, I understand that we need to return a Struct with the number and hash from the `starting`, `current` and `highest` blocks of the sync status.

From looking at `sync_one_block` from the `sync_blocks.rs` file, I see that we can get some info on the syncing state by calling `backend.meta().current_syncing_tips()`, but I'm a bit confused with what this Vec actually gets us for the Syncing status we need to return. My initial guess is that out of these items present in the Vec: 
 - the one with the lowest block number is the `starting`.
 - the one marked as `operating_header`, in that same `sync_one_block` function, is the `current`.
 - the one with the highest block number is the `highest`.
 
Am I correct, or do I need to get this information from a different place?

**Comment by abdelhamidbakhta** [comment]
> sync_blocks

@tdelabro can you help @zediogoviana please ?

**Comment by tdelabro** [comment]
Sure.

Madara is two chains, one inside the other. The substrate blocks wrap the statknet one with a 1 for 1 mapping between those.
So your current block can be retrieved using one of `current_block_number` or `current_block_hash` already implemented in `crates/client/rpc/src/lib.rs`.
Concerning `starting` and `highest`, I believe their value will depend on way you chose to sync your chain, more here: https://substrate.stackexchange.com/questions/334/what-kinds-of-sync-mechanisms-does-substrate-implement
But the logic will stay the same, get `starting` or `highest` substrate block and look into it to know the hash and number of the wrapped starknet block it contains.

So the question is now: How do you find those substate blocks.
There is a `system_syncState` RPC endpoint that had been added in this [PR](https://github.com/paritytech/substrate/pull/7315)
It is present on madara right now
```shell
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"system_syncState","params":[],"id":1}' localhost:9933
{"jsonrpc":"2.0","result":{"startingBlock":0,"currentBlock":2,"highestBlock":2},"id":1}%   
```

What I would recommend is for you to look into the code executed by `system_syncState` and take inspiration in order to retrieve the same data and then create the starknet data you need

**Comment by tdelabro** [comment]
In `/Users/tdelabro/Documents/code/starkware/madara/crates/node/src/service.rs`:
```rust
    let (network, system_rpc_tx, tx_handler_controller, network_starter, sync_service) =
        sc_service::build_network(sc_service::BuildNetworkParams {
            config: &config,
            client: client.clone(),
            transaction_pool: transaction_pool.clone(),
            spawn_handle: task_manager.spawn_handle(),
            import_queue,
            block_announce_validator_builder: None,
            warp_sync_params: Some(WarpSyncParams::WithProvider(warp_sync)),
        })?;
```
You get `system_rpc_tx`, it can be used to call the substrate System RPC client, like this:

```rust
	async fn system_sync_state(&self) -> RpcResult<SyncState<<B::Header as HeaderT>::Number>> {
		let (tx, rx) = oneshot::channel();
		let _ = system_rpc_tx.unbounded_send(Request::SyncState(tx));
		rx.await.map_err(|e| JsonRpseeError::to_call_error(e))
	}
```

You will get the expected struct:
```rust
pub struct SyncState<Number> {
	/// Height of the block at which syncing started.
	pub starting_block: Number,
	/// Height of the current best block of the node.
	pub current_block: Number,
	/// Height of the highest block in the network.
	pub highest_block: Number,
}
```

So all you have to do is to add this `system_rpc_tx` to `StarknetDeps` (in `crates/node/src/rpc/starknet.rs`) struct and then to use it in `crates/node/src/rpc/mod.rs` in order to create a `Starknet` struct (defined in `crates/client/rpc/src/lib.rs`). Then you can define your method and use the code snippet I gave you to query the System RPC server inside your Sarknet RPC server.

Or, if you don't want to rely on the underlying substrate System RPC implem, you can use  the `sync_service` directly instead, pass it to `StarknetDeps` and `Starknet` and then, use it here to directly query the syncing state yourselves.
You will have to remind the `starting_block` yourselves somewhere and then use a similar logic to:
```rust
	match sync_service.best_seen_block().await {
					Ok(best_seen_block) => {
						let best_number = client.info().best_number;
						let _ = sender.send(SyncState {
							starting_block,
							current_block: best_number,
							highest_block: best_seen_block.unwrap_or(best_number),
						});
					},
					Err(_) => log::error!("`SyncingEngine` shut down"),
				}
```

**Comment by zediogoviana** [comment]
Thanks for the explanation @tdelabro! I'll work on it 👌

**Comment by zediogoviana** [comment]
For the second option, when would we be storing/updating the `starting_block`?

**Comment by zediogoviana** [comment]
Hey @tdelabro, I've faced a problem with implementing the second approach you mentioned. 
Basically `sync_service.best_seen_block()` is an `async` function, and the place we need to be calling it is not. We can't also make it async because `fn syncing(&self) -> RpcResult<bool>` is a Trait.

I've tried using `futures::executor::block_on(self.sync_service.best_seen_block())` but the execution completely blocks at this point, without ever being fulfilled. Here's a [small explanation](https://stackoverflow.com/a/73273820/8733796) of what's happening. I've seen several references to using `tokio`, and I see that Pathfinder is also using it, but I'm not sure it could be a good solution for this case.

For the first approach, since `system_sync_state` is also `async`, I suspect the same problem still holds.

Do you have any extra pointers that could help with this?

**Comment by tdelabro** [comment]
@zediogoviana dm me on telegram @timothee_delabrouille and let's have a call together

**Comment by zediogoviana** [comment]
Hey @tdelabro! 
Yep, you were right! I was able to change the trait to make it async... The thing I was missing before was an extra line with `#[async_trait]`.

I believe the only missing part, now, is to get the block_hash from the respective number (to return `starting_block_num`, `starting_block_hash`, etc). Can you tell me which function I need to call?

**Comment by zediogoviana** [comment]
Hey @tdelabro! I should be able to open a PR today
