### ISSUE TITLE
Use real sequencer address in block header

### ISSUE THREAD

**Issue by LucasLvy** [keep-starknet-strange/madara#243]
# Description

The sequencer that proposes the block has to include his address in the block header. Here we need a way to use a Starknet account in substrate and store this address in the block header.

# Acceptance criteria

* The sequencer can use a Starknet account
* Its address is store in the block header

**Comment by LucasLvy** [comment]
yes assigned it to you

**Comment by dbejarano820** [comment]
Hey @LucasLvy, just checking the approach I'm planning to take is the desired one.

We could have the client get the desired sequencer address from an env variable and then through the runtime api set it in a storage value as soon as possible. Then we could use this value instead of the hardcoded one.

**Comment by dbejarano820** [comment]
Still WIP

**Comment by LucasLvy** [comment]
You already have an issue and I don't see an open PR so is it fine unassign this issue ?
