### ISSUE TITLE
feat(test): create fixture and tests for cases where there are too many pending transactions or events

### ISSUE THREAD

**Issue by Eikix** [keep-starknet-strange/madara#305]
# Feature Request

**Describe the Feature Request**

Currently, it is possible for transactions to fail if PendingTransactions storage is full. 
We'll need to reproduce in testing environment the case where this storage is full and properly generate the corresponding error.

Same goes for events.

**Describe Preferred Solution**

It could be created using the mock.rs file architecture.

Ref: https://github.com/keep-starknet-strange/madara/tree/main/crates/pallets/starknet/src/lib.rs#L374
Ref: https://github.com/keep-starknet-strange/madara/tree/main/crates/pallets/starknet/src/tests/mock.rs#L105

**Comment by tdelabro** [comment]
In order to mock those values in the `TestRuntime` in `mock.rs` they have to be part of the `Config` traits.
For now we use `MaxTransactions`, a value hardcoded in `crates/primitives/starknet/src/block/mod.rs`.

We need to make this one and the other constants used to bound our vector configurable.

blocked by #395

**Comment by tdelabro** [comment]
Deemed unnecessary after a talk with @abdelhamidbakhta
