### ISSUE TITLE
bug: block hash out of range

### ISSUE THREAD

**Issue by xJonathanLEI** [keep-starknet-strange/madara#381]
# Bug Report

**Madara version:**

`349e7c1044eb9d715a6b06d259678ec9c4dd49fd`

**Current behavior:**

Block hashes (or maybe other hashes too; haven't tested) reported are full 256-bit hashes.

**Expected behavior:**

All hashes should be bounded by the prime to be valid field elements.

**Steps to reproduce:**

1. Run Maara with `--dev`:
   ```console
   cargo run -- --dev
   ```
2. Query the latest block hash:
   ```console
   curl "http://localhost:9933/" -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","id":1,"method":"starknet_blockHashAndNumber","params":[]}'
   ```
3. Check that the resulting block hash is 256-bit.

**Related code:**

N/A

**Other information:**

N/A

**Comment by ClementWalter** [comment]
does this mean that hash return should be `hash % P` instead?

**Comment by ClementWalter** [comment]
The issue is [here](../blob/main/crates/client/rpc/src/lib.rs#L137) if I'm right

```
        Ok(BlockHashAndNumber { block_hash: format!("{:#x}", block_hash), block_number })
```

**Comment by tdelabro** [comment]
The problem is not RPC related. Our whole codebase uses U256 and H256 instead of Felts. We did it initially because it was more handy but is back firing now.

In order to fix this:
In `crates/primitives/starknet/src/block/header.rs`, we must change this function.
```
    #[must_use]
    pub fn hash(&self) -> H256 {
        H256::from_slice(frame_support::Hashable::blake2_256(&self.block_number.encode()).as_slice())
    }
```
Its signature should return a Felt and its implem should respect the starknet specification defined here: https://docs.starknet.io/documentation/architecture_and_concepts/Blocks/header/#block_hash

Then we have to change everything that uses this type downstream: `BlockHeader` type definition, runtime storage, backend and rpc implem.

A problem we will have is that substrate expects some traits for the types it accepts in its storage. I think we will have to define our own `SubstrateFelt(Felt)` newtype.
I think such a type already exists with `Felt252Wrapper(pub U256);`  defined in `crates/primitives/starknet/src/execution/program_wrapper.rs`. I believe this is the type we should store in the runtime. But when using it in our program we should convert it to `cairo_vm::felt::Felt252`.

**Comment by tdelabro** [comment]
The core of our logic is to interact with `Blockifier` which in turn call `cairo-vm`. So we need to use `cairo_vm::felt::Felt252` at some point, as it is the type expected by those libs. Therefore I think it is better to keep on with the Felt type defined by those libs, and propagate it along our codebase. 

On the other hand, we are going to use `starknet-rs` types for the RPC layer, so we will probably need to convert it to your `FieldElement` at some point. But probably only for the RPC layer.

Wdyt?

**Comment by ClementWalter** [comment]
see also https://github.com/keep-starknet-strange/madara/issues/128

**Comment by tdelabro** [comment]
@xJonathanLEI totally
