### ISSUE TITLE
Add check in the rpc that the class isn't already declared

### ISSUE THREAD

**Issue by LucasLvy** [keep-starknet-strange/madara#663]
# Description

Everytime a declare transaction is sent madara will process it regardless of wether it's already declared or not. This should not be the case and we should check in the RPC if the class is already declared. If it is the rpc should return an error: `Class already declared`.

In order to check that you can use the runtime api like so:
```rs
self
      .overrides
      .for_block_hash(self.client.as_ref(), substrate_block_hash)
      .contract_class_by_class_hash(substrate_block_hash, class_hash.into())
```
If the value is `Some` then you should return an error `Class already declared` else you can proceed with the normal flow.

**Comment by bajpai244** [comment]
I can take this ser 🙌

**Comment by chirag-bgh** [comment]
@bajpai244 are you still working on this?

**Comment by bajpai244** [comment]
Hello @chirag-bgh, I was travelling back from a conference, so was away from keyboard.

I will attempt this today :)

**Comment by ClementWalter** [comment]
@LucasLvy we talked about this and the current behavior on starknet mainnet/testnet is just to process the tx as it if was the first time. If we definitely can check if it is already declared to avoid useless compute, I think that for now we need to stick to the ecosystem de facto standard, ie responding with a success and the expected object

**Comment by bajpai244** [comment]
@ClementWalter, as discussed, according to the Starknet spec, there should be an error emitted by the sequencer.

Attaching the [link](https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_write_api.json#L146) here for people following this issue.

**Comment by bajpai244** [comment]
Hello everyone, so update on the task and the current blocker.

**Update:** the logic is complete, I have a test, and we return with the correct error code.

**Blocker:** 

Since, the class hash **"0x372ee6669dc86563007245ed7343d5180b96221ce28f44408cff2898038dbd"**  has already been declared [here](https://github.com/keep-starknet-strange/madara/blob/3678b42e7d9560a365f4ef49e01910e14881f161/tests/tests/test-rpc/test-starknet-rpc.ts#L732), hence [this](https://github.com/keep-starknet-strange/madara/blob/3678b42e7d9560a365f4ef49e01910e14881f161/tests/tests/test-rpc/test-starknet-rpc.ts#L796) test will fail.

So, to tackle that, I am trying to deploy some other contracts from the Madara cairo contract [builds](https://github.com/keep-starknet-strange/madara/tree/main/cairo-contracts/build), till I have tried Counter.json and ERC721.json.

Interestingly, if I declare them with [this](https://github.com/keep-starknet-strange/madara/blob/3678b42e7d9560a365f4ef49e01910e14881f161/tests/tests/test-rpc/test-starknet-rpc.ts#L803) class hash, which has been used above as well in the test, the declare pass { given I skip the first declare, otherwise an already deployed error will propagate }

But, if I declare them with their original class hash, the declaration fails:
BadSignature

![telegram-cloud-photo-size-5-6091445347781031406-y](https://github.com/keep-starknet-strange/madara/assets/41180869/556b9166-54b3-4081-ad88-bf11513e493a)

It fails on validation at the account contract, @greged93 came up with more info on it:
```
Signature 028dc04b988a675b1bcd79ac4c250dd9ac94df7d38e13b99b73e6fd3787416490618139a9639ddc4bd2efdb5b4acf28d4f5df46d1a790cd3d273d43d4dc24660, is invalid, with respect to the public key 1526957205177128997396356218568809711667570742336855665462700938352069314994, 
    and the message hash 3373488621799458379249726602119906446677633581575170863478276233453773209349.
```
Even in case of ERC20 declare, it fails if use any other class hash! How was **"0x372ee6669dc86563007245ed7343d5180b96221ce28f44408cff2898038dbd"** obtained as a class hash, and does anyone has any context on where this error could be orginating from?

**Comment by bajpai244** [comment]
Update: the above issue has been resolved, the trick is to use `starkli` for computing these class hashes.
