### ISSUE TITLE
dev: Use argent account in benchmark

### ISSUE THREAD

**Issue by LucasLvy** [keep-starknet-strange/madara#781]
For now we're using the simple account that doesn't have any validation logic. We want to use the argent account with a signature verification to have a real benchmark.

tasks:
- Change the address of the account used in the benchmark to the argent account address
- Use starknet.js to sign every transaction

**Comment by Pilouche** [comment]
Hi @LucasLvy, can I take this one please ?

**Comment by Pilouche** [comment]
@LucasLvy should I also keep using the `extrisinc` methods (`transfer()`, `mintERC721()`) as well ? Or is it possible to use `starknet.js` to send the transactions if it won't affect the benchmark results ? 
Asking this because I wanted to use the `signAndSend()` method from `polkadot` on the extrinsic tx but it seems pretty cumbersome to instantiate this `export type AddressOrPair = IKeyringPair | string | AccountId | Address;` type passed as args for the `signAndSend()` method. I didn't find a way to do it yet.
