### ISSUE TITLE
feat: tendermint for substrate

### ISSUE THREAD

**Issue by AbdelStark** [keep-starknet-strange/madara#896]
### Description

The goal of this issue is to implement the Tendermint consensus algorithm in a way that is compatible with the Substrate framework. This will allow Madara to leverage the benefits of both the Tendermint consensus and the Substrate's modular framework.

### Background

Tendermint is a Byzantine Fault Tolerant (BFT) middleware that takes a state transition machine - written in any programming language - and securely replicates it on many machines. Substrate, on the other hand, is a modular framework that enables you to create purpose-built blockchains by composing custom or pre-built components.

### Tasks

1. **Research**: Understand the Tendermint consensus algorithm and how it can be integrated with the Substrate framework.
2. **Design**: Create a design document detailing how the Tendermint consensus will be implemented in Madara. This should include any necessary changes to the existing architecture.
3. **Implementation**: Implement the design, ensuring that the new consensus algorithm is fully compatible with Substrate.
4. **Testing**: Write comprehensive tests to ensure the new consensus algorithm works as expected and does not introduce any regressions.
5. **Documentation**: Update the project documentation to reflect the new consensus algorithm.

### Acceptance Criteria

- The Tendermint consensus algorithm is fully implemented and compatible with the Substrate framework.
- The implementation passes all tests.
- The project documentation is updated to reflect the new consensus algorithm.

### Resources

- [Tendermint Core Documentation](https://docs.tendermint.com)
- [Substrate Documentation](https://substrate.dev/docs/en/)

**Comment by adizere** [comment]
Glad to help here! Our team is maintaining and actively developing [CometBFT](https://github.com/cometbft/cometbft/), the state of the art implementation of Tendermint consensus algorithm (used throughout the Cosmos ecosystem and beyond).

Note that the documentation linked in the original post to https://docs.tendermint.com/ is no longer maintained. Tendermint Core has been discontinued since December 2022. [Reference](https://github.com/tendermint/tendermint/issues/9972#issuecomment-1412453755). CometBFT is a fork and successor of Tendermint Core, so most projects switched to that.

**Comment by tdelabro** [comment]
repository archived in favor of https://github.com/madara-alliance/madara
