### ISSUE TITLE
feat: display dev account info on startup 

### ISSUE THREAD

**Issue by glihm** [keep-starknet-strange/madara#927]
# Feature Request

**Describe the Feature Request**

In web3 tools starting local node we usually have quick access to dev accounts.
Would be great if madara can print this information out to avoid a user looking into
the code base for that.

**Describe Preferred Solution**

Ideally, printing the address and and private key associated to a pre-funded account.
From feedbacks I had from @apoorvsadana, [the account is argent class at address](https://github.com/glihm/madara/blob/6d92e605f0cb0784e6188f2779e0370a83cb621f/crates/node/src/constants.rs#L1C1-L1C1) `0x2`, with
[private and public key here](https://github.com/glihm/madara/blob/6d92e605f0cb0784e6188f2779e0370a83cb621f/tests/tests/constants.ts#L27).

**Related Code**

[Account info](https://github.com/glihm/madara/blob/6d92e605f0cb0784e6188f2779e0370a83cb621f/crates/node/src/constants.rs#L1C1-L1C1)

[Signer info](https://github.com/glihm/madara/blob/6d92e605f0cb0784e6188f2779e0370a83cb621f/tests/tests/constants.ts#L27)

I am not sure yet where this print must reside, [chain_spec](https://github.com/glihm/madara/blob/6d92e605f0cb0784e6188f2779e0370a83cb621f/crates/node/src/chain_spec.rs) can be a good starting point.

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

Yes :rocket:

**Comment by apoorvsadana** [comment]
Let's only print this extra information when the `--dev` flag is enabled

**Comment by a-moreira** [comment]
hey @glihm @apoorvsadana  ! since the node info printing at startup comes from Substrate itself (it's inside the `runner` [here](https://github.com/paritytech/substrate/blob/31491fa24164b1cc9fffd5f07f06f41c8fef437d/client/cli/src/runner.rs#L73)), I propose having this print inside the `new_full` function in Madara. I create a branch on my fork and will open a PR if you guys think it's good (file changes in my fork [here](https://github.com/a-moreira/madara/pull/1/files))

![Screenshot 2023-07-31 at 01 01 56](https://github.com/keep-starknet-strange/madara/assets/48456867/038ffa67-e8f3-4ffc-898b-53134d212236)

Note that in the print the address and key are being printed as Field elements, we need to convert back to hex.

**Comment by apoorvsadana** [comment]
Hey @a-moreira, that approach looks fine to me. You can create a PR and we can review it. @abdelhamidbakhta can you assign this issue to @a-moreira as well.

**Comment by a-moreira** [comment]
ok, it's here #941
