### ISSUE TITLE
feat: estimate_fee should make sure version has been tweaked

### ISSUE THREAD

**Issue by tdelabro** [keep-starknet-strange/madara#991]
# Feature Request

**Describe the Feature Request**

In order to avoid estimated tx to be republished on mainet by malicious node, it uses a tx version which is `actual_tx_version_number + 0x100000000000000000000000000000000`.

We currently don't enforce this on the estimate_fee logic

**Describe Preferred Solution**

It should probably be enforced both in the rpc client and the runtime logic

**Additional Context**

https://www.starknetjs.com/docs/guides/estimate_fees/

**Comment by gaetbout** [comment]
I can try this :)

**Comment by lana-shanghai** [comment]
> Can I try this one?

Yes sir! :)

**Comment by tdelabro** [comment]
@gaetbout I don't get your sidenote. What are the additional restrictions you are talking about?

**Comment by tdelabro** [comment]
Let ignore this for now, and open an issue after looking into the code if you find out it is not enforced

**Comment by gaetbout** [comment]
hey @tdelabro,
Correct me if I'm wrong, but if I understood correctly, I have to modify:
crates >> primitives >> starknet >> src >> transaction >> types.rs >> line 638.
But I see that the transaction version is of type u8. Thus the value won't fit. Should I then update the `struct InvokeTransaction` ?

**Comment by apoorvsadana** [comment]
@gaetbout, we get to know if the version is an actual version or an estimate fee version using the `is_query` field inside `Transaction`. If it's true, we know that it's an estimate fee call. You can read more about the decision to do this over [here](https://github.com/xJonathanLEI/starknet-rs/issues/402#issuecomment-1625154934).

@tdelabro, I have a doubt though. Isn't this more of user/wallet level check to send the correct version in fee estimation. Because, even if we make the changes in the client/runtime side of the node and a wallet sends an `estimateFee` call with version `0x1`, the `estimateFee` call will fail, however, nothing is stopping the node from re sending the transaction as an `invoke` which will then include the transaction

**Comment by tdelabro** [comment]
@apoorvsadana The signature is supposed to be for a tx with `version: 0x100000000000000000000000000000001`, so the node won't be able to reuse it.

@gaetbout yeah, the transaction types are kind of shitty right now. It will be fixed soon but it may be a blocker for this specific issue.

**Comment by tdelabro** [comment]
@xJonathanLEI How are you handling the `estimateFee` thing? Why doing it by a combination of a `u8` capped version and a `is_query` flag, when the user is supposed to sign a huge value (`0x100000000000000000000000000000001`) as is `tx_version`?

**Comment by xJonathanLEI** [comment]
Sorry but I don't think I understand the question?

If you're asking about deserializing and detecting that users are sending a "query-only" version, `starknet-rs` provides `is_query` for downstream applications to use. When users send a huge version, `is_query` is true. Applications can then recover the "raw" (huge) version value based on the version variant and `is_query`.

For example, if you're receiving a `BroadcastedDeclareTransactionV2` and `is_query` is `true`, you know the user is actually using raw version value `0x100000000000000000000000000000002` instead of `0x2`. `starknet-rs` currently does not (but it should) provide a way of performing this recovery.

If you're asking about how `starknet-rs` itself is making use of this for _SENDING_ transactions - it does not. At the moment `starknet-rs` does not make use of "query-only" (huge) tx versions. But I guess this is not what you're concerned about as you're using `starknet-rs` on the server side (i.e. _RECEIVING_ transactions).

**Comment by apoorvsadana** [comment]
> @apoorvsadana The signature is supposed to be for a tx with version: 0x100000000000000000000000000000001, so the node won't be able to reuse it.

Yes, but if the user/wallet signs with `0x1` instead, how does the check in this issue add any security?

**Comment by xJonathanLEI** [comment]
Technically Madara should recover the _actual_ version submitted with the logic I mentioned above, and validates that the user's signature is valid under the recovered version. You can't submit a huge version and actually sign it with `0x1`. It fails signature validation.

**Comment by tdelabro** [comment]
> For example, if you're receiving a BroadcastedDeclareTransactionV2 and is_query is true, you know the user is actually using raw version value 0x100000000000000000000000000000002 instead of 0x2. starknet-rs currently does not (but it should) provide a way of performing this recovery.

This is what I was looking for. Ty

**Comment by apoorvsadana** [comment]
That's not what I meant, sorry maybe I didn't word it correctly. The user signs the message with the version he is submitting. However, from what I understand, this issue is created to prevent estimateFee transactions from being replayed as an invoke transaction (even though the user didn't intend to do so). So forcing the huge version check will cause estimateFee to fail if the user sends any other version number like `0x1` (which is used for the actual transaction). But, if I understand it correctly, even if the estimateFee fails, the malicious node can still send this transaction as an invoke transaction and as such, no security will be added even if we add the check inside estimateFee.

I can see an advantage of this check where app developers will know during development that they are sending the incorrect version during estimateFee and it will save them from adding vulnerability to their code. However, if it so happens that someone submits an estimateFee with `0x1`, I believe this will not add any security.

**Comment by tdelabro** [comment]
> But, if I understand it correctly, even if the estimateFee fails, the malicious node can still send this transaction as an invoke transaction and as such, no security will be added even if we add the check inside estimateFee.

He can send it but the signature is for the huge version number. So it won't be accepted by the runtime as a regular transaction. And if he change the tx_version for a regular one, it won't match the signature anymore.

**Comment by tdelabro** [comment]
I think the `is_query` trick is just a way for starknet_rs to reduce the size of it's payload. Two `u8` instead of a `u256`. Correct me if I'm wrong @xJonathanLEI

**Comment by apoorvsadana** [comment]
> He can send it but the signature is for the huge version number. So it won't be accepted by the runtime as a regular transaction. And if he change the tx_version for a regular one, it won't match the signature anymore.

I am not sure if I am missing something here. This is the problem that I think we are solving, before the fix in this issue the user will send estimateFee calls with version `0x1` and sign it with version `0x1` as well and they will go through. However, since the version and signature are both of `0x1`, a malicious node can take this transaction and send it as an `invoke` transaction. Is this the problem we are trying to solve?

**Comment by tdelabro** [comment]
After we do the fix, the user will get an error and won't keep sending that valid tx to the node. He will learn from his error and send them with the huge version number when he wants to estimate_fee.

**Comment by apoorvsadana** [comment]
Understood. So it's a way to keep app developers informed about a possible vulnerability in their code.

**Comment by tdelabro** [comment]
Yup. And hopefully, they will use a lib that prevents them from do this kind of mistake. But in case they do it manually, they will get an error

**Comment by gaetbout** [comment]
GM @tdelabro, @apoorvsadana,

Did a first draft, could you let me know if this looks correct (don't spend too much time).
LMK if I missed something

You can find it here: 
https://github.com/keep-starknet-strange/madara/compare/main...gaetbout:madara:feat/estimate_fee_correct_version

Thanks in advance,
G.

**Comment by apoorvsadana** [comment]
@gaetbout just checked it, the approach looks fine to me :) maybe we can wait for @tdelabro to have a look as well
